# Generated by Django 3.1.7 on 2021-07-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldHappinessReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=200, unique=True, verbose_name='Country name')),
                ('rank', models.CharField(max_length=100, unique=True, verbose_name='Rank')),
                ('ladderScore', models.CharField(max_length=200, verbose_name='Ladder score')),
                ('healthyLifeExpectancy', models.CharField(max_length=200, verbose_name='Healthy life expectancy')),
                ('generosity', models.CharField(max_length=200, verbose_name='Generosity')),
                ('gdp', models.CharField(max_length=200, verbose_name='Logged GDP per capita')),
            ],
        ),
    ]
